name: Publish Chrome Extension

on:
  release:
    types: [created]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: zip -r ymr.zip * -x *.md -x package*.json -x .*/

    - uses: actions/upload-artifact@v3
      with:
        name: zip
        path: ymr.zip
        retention-days: 10

  publish:
    needs: zip
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: zip

    - uses: trmcnvn/chrome-addon@v2
      with:
        extension: ckmghhopnoeddmnlnploommajnnkhjjj
        zip: ymr.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
